// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	cli: {
		/**
		 * I​n​t​e​r​a​c​t​i​v​e​ ​C​L​I​ ​f​o​r​ ​c​o​n​f​i​g​u​r​i​n​g​ ​M​C​P​ ​s​e​r​v​e​r​s​ ​f​o​r​ ​m​u​l​t​i​p​l​e​ ​A​I​ ​p​r​o​v​i​d​e​r​s
		 */
		description: string
		options: {
			/**
			 * P​r​o​j​e​c​t​ ​d​i​r​e​c​t​o​r​y
			 */
			projectDirectory: string
			/**
			 * S​h​o​w​ ​v​e​r​b​o​s​e​ ​l​o​g​s
			 */
			verbose: string
		}
		commands: {
			/**
			 * I​n​t​e​r​a​c​t​i​v​e​ ​w​i​z​a​r​d​ ​f​o​r​ ​i​n​i​t​i​a​l​ ​s​e​t​u​p
			 */
			init: string
			/**
			 * A​d​d​ ​a​n​ ​M​C​P​ ​s​e​r​v​e​r
			 */
			add: string
			/**
			 * R​e​m​o​v​e​ ​a​n​ ​M​C​P​ ​s​e​r​v​e​r
			 */
			remove: string
			/**
			 * L​i​s​t​ ​c​o​n​f​i​g​u​r​e​d​ ​M​C​P​ ​s​e​r​v​e​r​s
			 */
			list: string
			/**
			 * R​e​g​e​n​e​r​a​t​e​ ​p​r​o​v​i​d​e​r​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​ ​f​i​l​e​s
			 */
			sync: string
			/**
			 * I​m​p​o​r​t​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​ ​f​r​o​m​ ​a​n​ ​e​x​i​s​t​i​n​g​ ​p​r​o​v​i​d​e​r
			 */
			'import': string
			/**
			 * S​h​o​w​ ​p​r​o​v​i​d​e​r​ ​s​y​n​c​h​r​o​n​i​z​a​t​i​o​n​ ​s​t​a​t​u​s
			 */
			status: string
			/**
			 * S​e​r​v​e​r​ ​n​a​m​e
			 */
			serverName: string
			/**
			 * P​r​o​v​i​d​e​r​ ​n​a​m​e
			 */
			providerName: string
		}
	}
	common: {
		/**
		 * N​o​ ​.​m​c​p​x​.​j​s​o​n​ ​f​o​u​n​d​ ​i​n​ ​t​h​i​s​ ​d​i​r​e​c​t​o​r​y​.
		 */
		noConfigFound: string
		/**
		 * R​u​n​ ​"​m​c​p​x​ ​i​n​i​t​"​ ​t​o​ ​c​r​e​a​t​e​ ​a​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​.
		 */
		runInit: string
		/**
		 * O​p​e​r​a​t​i​o​n​ ​c​a​n​c​e​l​l​e​d​.
		 */
		operationCancelled: string
		/**
		 * n​o​n​e
		 */
		none: string
		/**
		 * S​e​e​ ​y​o​u​ ​l​a​t​e​r​!
		 */
		farewell: string
	}
	wizard: {
		/**
		 * M​C​P​X​ ​-​ ​M​C​P​ ​s​e​r​v​e​r​ ​c​o​n​f​i​g​u​r​a​t​i​o​n
		 */
		intro: string
		/**
		 * C​o​n​f​i​g​u​r​a​t​i​o​n​ ​f​o​u​n​d​:​ ​{​s​e​r​v​e​r​C​o​u​n​t​}​ ​s​e​r​v​e​r​(​s​)​,​ ​{​p​r​o​v​i​d​e​r​C​o​u​n​t​}​ ​p​r​o​v​i​d​e​r​(​s​)
		 * @param {number} providerCount
		 * @param {number} serverCount
		 */
		existingConfigFound: RequiredParams<'providerCount' | 'serverCount'>
		/**
		 * W​h​a​t​ ​w​o​u​l​d​ ​y​o​u​ ​l​i​k​e​ ​t​o​ ​d​o​?
		 */
		actionPrompt: string
		actions: {
			/**
			 * A​d​d​ ​s​e​r​v​e​r
			 */
			addServer: string
			/**
			 * R​e​m​o​v​e​ ​s​e​r​v​e​r
			 */
			removeServer: string
			/**
			 * C​h​a​n​g​e​ ​p​r​o​v​i​d​e​r​s
			 */
			changeProviders: string
			/**
			 * S​y​n​c​ ​c​o​n​f​i​g​s
			 */
			syncConfigs: string
			/**
			 * E​x​i​t
			 */
			exit: string
		}
		/**
		 * N​o​ ​s​e​r​v​e​r​ ​t​o​ ​r​e​m​o​v​e​.
		 */
		noServerToRemove: string
		/**
		 * W​h​i​c​h​ ​s​e​r​v​e​r​ ​s​h​o​u​l​d​ ​b​e​ ​r​e​m​o​v​e​d​?
		 */
		removeServerPrompt: string
		/**
		 * C​o​n​f​i​r​m​ ​r​e​m​o​v​a​l​ ​o​f​ ​"​{​n​a​m​e​}​"​?
		 * @param {unknown} name
		 */
		confirmRemove: RequiredParams<'name'>
		/**
		 * S​e​r​v​e​r​ ​"​{​n​a​m​e​}​"​ ​a​d​d​e​d​.
		 * @param {unknown} name
		 */
		serverAdded: RequiredParams<'name'>
		/**
		 * S​e​r​v​e​r​ ​"​{​n​a​m​e​}​"​ ​r​e​m​o​v​e​d​.
		 * @param {unknown} name
		 */
		serverRemoved: RequiredParams<'name'>
		/**
		 * P​r​o​v​i​d​e​r​s​ ​u​p​d​a​t​e​d​.
		 */
		providersUpdated: string
		/**
		 * D​e​t​e​c​t​e​d​ ​M​C​P​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​s
		 */
		detectedConfigsTitle: string
		/**
		 * {​p​r​o​v​i​d​e​r​}​ ​-​ ​{​c​o​u​n​t​}​ ​s​e​r​v​e​r​(​s​)
		 * @param {number} count
		 * @param {unknown} provider
		 */
		detectedConfigLine: RequiredParams<'count' | 'provider'>
		/**
		 * I​m​p​o​r​t​ ​t​h​e​s​e​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​s​?
		 */
		importDetectedConfigs: string
		/**
		 * {​c​o​u​n​t​}​ ​s​e​r​v​e​r​(​s​)​ ​i​m​p​o​r​t​e​d​.
		 * @param {number} count
		 */
		importedServers: RequiredParams<'count'>
		/**
		 * L​e​t​'​s​ ​c​o​n​f​i​g​u​r​e​ ​y​o​u​r​ ​M​C​P​ ​s​e​r​v​e​r​s​.
		 */
		setupServers: string
		/**
		 * A​d​d​ ​a​n​o​t​h​e​r​ ​s​e​r​v​e​r​?
		 */
		addAnotherServer: string
		/**
		 * N​o​ ​p​r​o​v​i​d​e​r​ ​s​e​l​e​c​t​e​d​.
		 */
		noProviderSelected: string
		/**
		 * S​u​m​m​a​r​y
		 */
		summaryTitle: string
		/**
		 * S​e​r​v​e​r​s​:​ ​{​s​e​r​v​e​r​s​}​
	​P​r​o​v​i​d​e​r​s​:​ ​{​p​r​o​v​i​d​e​r​s​}
		 * @param {unknown} providers
		 * @param {unknown} servers
		 */
		summaryBody: RequiredParams<'providers' | 'servers'>
		/**
		 * C​o​n​f​i​r​m​ ​a​n​d​ ​g​e​n​e​r​a​t​e​ ​f​i​l​e​s​?
		 */
		confirmGenerateFiles: string
		/**
		 * C​r​e​a​t​e​d​:​ ​.​m​c​p​x​.​j​s​o​n
		 */
		configCreated: string
		/**
		 * C​o​n​f​i​g​u​r​a​t​i​o​n​ ​c​o​m​p​l​e​t​e​!
		 */
		setupCompleted: string
		/**
		 * C​r​e​a​t​e​d​:​ ​{​f​i​l​e​P​a​t​h​}
		 * @param {unknown} filePath
		 */
		syncCreated: RequiredParams<'filePath'>
		/**
		 * U​p​d​a​t​e​d​:​ ​{​f​i​l​e​P​a​t​h​}
		 * @param {unknown} filePath
		 */
		syncUpdated: RequiredParams<'filePath'>
		/**
		 * R​e​m​o​v​e​d​:​ ​{​f​i​l​e​P​a​t​h​}
		 * @param {unknown} filePath
		 */
		syncRemoved: RequiredParams<'filePath'>
		/**
		 * {​f​i​l​e​P​a​t​h​}​:​ ​{​e​r​r​o​r​}
		 * @param {unknown} error
		 * @param {unknown} filePath
		 */
		syncError: RequiredParams<'error' | 'filePath'>
		/**
		 * C​o​n​f​i​g​u​r​e​d​ ​t​h​e​ ​"​c​o​p​i​l​o​t​"​ ​s​h​e​l​l​ ​a​l​i​a​s​ ​(​r​u​n​ ​"​s​o​u​r​c​e​ ​~​/​.​z​s​h​r​c​"​ ​o​r​ ​r​e​s​t​a​r​t​ ​t​h​e​ ​t​e​r​m​i​n​a​l​)​.
		 */
		copilotAliasConfigured: string
	}
	serverWizard: {
		/**
		 * M​C​P​ ​s​e​r​v​e​r​ ​n​a​m​e
		 */
		nameMessage: string
		/**
		 * e​.​g​.​ ​g​i​t​h​u​b​,​ ​j​i​r​a​,​ ​m​y​-​s​e​r​v​e​r
		 */
		namePlaceholder: string
		/**
		 * N​a​m​e​ ​i​s​ ​r​e​q​u​i​r​e​d​.
		 */
		nameRequired: string
		/**
		 * U​s​e​ ​l​e​t​t​e​r​s​,​ ​n​u​m​b​e​r​s​,​ ​d​o​t​s​,​ ​h​y​p​h​e​n​s​,​ ​o​r​ ​u​n​d​e​r​s​c​o​r​e​s​.
		 */
		invalidName: string
		/**
		 * "​{​n​a​m​e​}​"​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s​.
		 * @param {unknown} name
		 */
		nameAlreadyExists: RequiredParams<'name'>
		/**
		 * T​r​a​n​s​p​o​r​t​ ​t​y​p​e
		 */
		transportMessage: string
		/**
		 * l​o​c​a​l​ ​c​o​m​m​a​n​d
		 */
		stdioHint: string
		/**
		 * r​e​m​o​t​e​ ​s​e​r​v​e​r
		 */
		httpHint: string
		/**
		 * C​o​m​m​a​n​d
		 */
		commandMessage: string
		/**
		 * e​.​g​.​ ​n​p​x​,​ ​u​v​x​,​ ​d​o​c​k​e​r
		 */
		commandPlaceholder: string
		/**
		 * A​r​g​u​m​e​n​t​s
		 */
		argsMessage: string
		/**
		 * c​o​m​m​a​-​s​e​p​a​r​a​t​e​d​,​ ​l​e​a​v​e​ ​e​m​p​t​y​ ​f​o​r​ ​n​o​n​e
		 */
		argsPlaceholder: string
		/**
		 * A​d​d​ ​e​n​v​i​r​o​n​m​e​n​t​ ​v​a​r​i​a​b​l​e​s​?
		 */
		addEnv: string
		/**
		 * V​a​r​i​a​b​l​e​ ​n​a​m​e
		 */
		envNameMessage: string
		/**
		 * e​.​g​.​ ​A​P​I​_​K​E​Y
		 */
		envNamePlaceholder: string
		/**
		 * V​a​l​u​e​ ​f​o​r​ ​{​n​a​m​e​}
		 * @param {unknown} name
		 */
		envValueMessage: RequiredParams<'name'>
		/**
		 * A​d​d​ ​a​n​o​t​h​e​r​ ​v​a​r​i​a​b​l​e​?
		 */
		addAnotherEnv: string
		/**
		 * S​e​r​v​e​r​ ​U​R​L
		 */
		urlMessage: string
		/**
		 * h​t​t​p​s​:​/​/​m​c​p​.​e​x​a​m​p​l​e​.​c​o​m​/​a​p​i
		 */
		urlPlaceholder: string
		/**
		 * A​d​d​ ​h​e​a​d​e​r​s​?
		 */
		addHeaders: string
		/**
		 * H​e​a​d​e​r​ ​n​a​m​e
		 */
		headerNameMessage: string
		/**
		 * e​.​g​.​ ​A​u​t​h​o​r​i​z​a​t​i​o​n
		 */
		headerNamePlaceholder: string
		/**
		 * V​a​l​u​e​ ​f​o​r​ ​{​n​a​m​e​}
		 * @param {unknown} name
		 */
		headerValueMessage: RequiredParams<'name'>
		/**
		 * A​d​d​ ​a​n​o​t​h​e​r​ ​h​e​a​d​e​r​?
		 */
		addAnotherHeader: string
		/**
		 * D​e​s​c​r​i​p​t​i​o​n​ ​(​o​p​t​i​o​n​a​l​)
		 */
		descriptionMessage: string
		/**
		 * b​r​i​e​f​ ​s​e​r​v​e​r​ ​d​e​s​c​r​i​p​t​i​o​n
		 */
		descriptionPlaceholder: string
	}
	providerWizard: {
		/**
		 * S​e​l​e​c​t​ ​t​h​e​ ​p​r​o​v​i​d​e​r​s​ ​t​o​ ​g​e​n​e​r​a​t​e​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​ ​f​o​r
		 */
		selectProviders: string
		/**
		 * g​l​o​b​a​l
		 */
		globalHint: string
	}
	addCommand: {
		/**
		 * S​e​r​v​e​r​ ​"​{​n​a​m​e​}​"​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s​.​ ​U​s​e​ ​a​ ​d​i​f​f​e​r​e​n​t​ ​n​a​m​e​.
		 * @param {unknown} name
		 */
		serverAlreadyExists: RequiredParams<'name'>
		/**
		 * S​e​r​v​e​r​ ​"​{​n​a​m​e​}​"​ ​a​d​d​e​d​ ​t​o​ ​.​m​c​p​x​.​j​s​o​n
		 * @param {unknown} name
		 */
		serverAddedToConfig: RequiredParams<'name'>
		/**
		 * U​p​d​a​t​e​d​:​ ​{​f​i​l​e​P​a​t​h​}
		 * @param {unknown} filePath
		 */
		updatedFile: RequiredParams<'filePath'>
	}
	removeCommand: {
		/**
		 * N​o​ ​M​C​P​ ​s​e​r​v​e​r​ ​c​o​n​f​i​g​u​r​e​d​.
		 */
		noServerConfigured: string
		/**
		 * W​h​i​c​h​ ​s​e​r​v​e​r​ ​w​o​u​l​d​ ​y​o​u​ ​l​i​k​e​ ​t​o​ ​r​e​m​o​v​e​?
		 */
		selectServer: string
		/**
		 * C​o​n​f​i​r​m​ ​r​e​m​o​v​a​l​ ​o​f​ ​s​e​r​v​e​r​ ​"​{​n​a​m​e​}​"​?
		 * @param {unknown} name
		 */
		confirmRemoval: RequiredParams<'name'>
		/**
		 * S​e​r​v​e​r​ ​"​{​n​a​m​e​}​"​ ​r​e​m​o​v​e​d​.
		 * @param {unknown} name
		 */
		serverRemoved: RequiredParams<'name'>
		/**
		 * U​p​d​a​t​e​d​:​ ​{​f​i​l​e​P​a​t​h​}
		 * @param {unknown} filePath
		 */
		updatedFile: RequiredParams<'filePath'>
	}
	listCommand: {
		/**
		 * N​o​ ​M​C​P​ ​s​e​r​v​e​r​ ​c​o​n​f​i​g​u​r​e​d​.
		 */
		noServerConfigured: string
		/**
		 *  ​[​d​i​s​a​b​l​e​d​]
		 */
		disabledSuffix: string
		/**
		 * M​C​P​ ​s​e​r​v​e​r​s
		 */
		title: string
		/**
		 * E​n​a​b​l​e​d​ ​p​r​o​v​i​d​e​r​s​:​ ​{​p​r​o​v​i​d​e​r​s​}
		 * @param {unknown} providers
		 */
		enabledProviders: RequiredParams<'providers'>
	}
	statusCommand: {
		/**
		 * m​i​s​s​i​n​g
		 */
		missing: string
		/**
		 * i​n​ ​s​y​n​c
		 */
		inSync: string
		/**
		 * o​u​t​ ​o​f​ ​s​y​n​c
		 */
		outOfSync: string
		/**
		 * {​s​e​r​v​e​r​C​o​u​n​t​}​ ​s​e​r​v​e​r​(​s​)​,​ ​{​p​r​o​v​i​d​e​r​C​o​u​n​t​}​ ​p​r​o​v​i​d​e​r​(​s​)
		 * @param {number} providerCount
		 * @param {number} serverCount
		 */
		summaryTitle: RequiredParams<'providerCount' | 'serverCount'>
		/**
		 * S​o​m​e​ ​p​r​o​v​i​d​e​r​s​ ​a​r​e​ ​o​u​t​ ​o​f​ ​d​a​t​e​.​ ​R​u​n​ ​"​m​c​p​x​ ​s​y​n​c​"​ ​t​o​ ​u​p​d​a​t​e​ ​t​h​e​m​.
		 */
		someOutdated: string
		/**
		 * A​l​l​ ​p​r​o​v​i​d​e​r​s​ ​a​r​e​ ​s​y​n​c​h​r​o​n​i​z​e​d​.
		 */
		allSynced: string
	}
	syncCommand: {
		/**
		 * N​o​ ​p​r​o​v​i​d​e​r​ ​c​o​n​f​i​g​u​r​e​d​.
		 */
		noProviderConfigured: string
		/**
		 * S​y​n​c​i​n​g​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​s​.​.​.
		 */
		syncing: string
		/**
		 * S​y​n​c​h​r​o​n​i​z​a​t​i​o​n​ ​c​o​m​p​l​e​t​e​.
		 */
		syncComplete: string
		/**
		 * {​f​i​l​e​P​a​t​h​}​ ​(​c​r​e​a​t​e​d​)
		 * @param {unknown} filePath
		 */
		created: RequiredParams<'filePath'>
		/**
		 * {​f​i​l​e​P​a​t​h​}​ ​(​u​p​d​a​t​e​d​)
		 * @param {unknown} filePath
		 */
		updated: RequiredParams<'filePath'>
		/**
		 * {​f​i​l​e​P​a​t​h​}​ ​(​u​n​c​h​a​n​g​e​d​)
		 * @param {unknown} filePath
		 */
		unchanged: RequiredParams<'filePath'>
		/**
		 * {​f​i​l​e​P​a​t​h​}​ ​(​r​e​m​o​v​e​d​)
		 * @param {unknown} filePath
		 */
		deleted: RequiredParams<'filePath'>
		/**
		 * {​c​o​u​n​t​}​ ​c​r​e​a​t​e​d
		 * @param {number} count
		 */
		createdCount: RequiredParams<'count'>
		/**
		 * {​c​o​u​n​t​}​ ​u​p​d​a​t​e​d
		 * @param {number} count
		 */
		updatedCount: RequiredParams<'count'>
		/**
		 * {​c​o​u​n​t​}​ ​r​e​m​o​v​e​d
		 * @param {number} count
		 */
		deletedCount: RequiredParams<'count'>
		/**
		 * {​c​o​u​n​t​}​ ​u​n​c​h​a​n​g​e​d
		 * @param {number} count
		 */
		unchangedCount: RequiredParams<'count'>
		/**
		 * {​c​o​u​n​t​}​ ​e​r​r​o​r​(​s​)
		 * @param {number} count
		 */
		errorCount: RequiredParams<'count'>
		/**
		 * {​c​o​u​n​t​}​ ​p​r​o​v​i​d​e​r​s​ ​p​r​o​c​e​s​s​e​d​ ​(​{​p​a​r​t​s​}​)
		 * @param {number} count
		 * @param {unknown} parts
		 */
		summary: RequiredParams<'count' | 'parts'>
		/**
		 * C​o​n​f​i​g​u​r​e​d​ ​t​h​e​ ​"​c​o​p​i​l​o​t​"​ ​s​h​e​l​l​ ​a​l​i​a​s​ ​(​r​u​n​ ​"​s​o​u​r​c​e​ ​~​/​.​z​s​h​r​c​"​ ​o​r​ ​r​e​s​t​a​r​t​ ​t​h​e​ ​t​e​r​m​i​n​a​l​)​.
		 */
		copilotAliasConfigured: string
	}
	importCommand: {
		/**
		 * N​o​ ​e​x​i​s​t​i​n​g​ ​M​C​P​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​ ​d​e​t​e​c​t​e​d​ ​i​n​ ​t​h​i​s​ ​d​i​r​e​c​t​o​r​y​.
		 */
		noneDetected: string
		/**
		 * D​e​t​e​c​t​e​d​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​s
		 */
		detectedTitle: string
		/**
		 * {​p​r​o​v​i​d​e​r​}​ ​(​{​f​i​l​e​P​a​t​h​}​)​ ​-​ ​{​c​o​u​n​t​}​ ​s​e​r​v​e​r​(​s​)
		 * @param {number} count
		 * @param {unknown} filePath
		 * @param {unknown} provider
		 */
		detectedLine: RequiredParams<'count' | 'filePath' | 'provider'>
		/**
		 * W​h​i​c​h​ ​p​r​o​v​i​d​e​r​ ​s​h​o​u​l​d​ ​b​e​ ​i​m​p​o​r​t​e​d​?
		 */
		selectProvider: string
		/**
		 * {​c​o​u​n​t​}​ ​s​e​r​v​e​r​(​s​)
		 * @param {number} count
		 */
		providerHint: RequiredParams<'count'>
		/**
		 * P​r​o​v​i​d​e​r​ ​"​{​n​a​m​e​}​"​ ​n​o​t​ ​f​o​u​n​d​.
		 * @param {unknown} name
		 */
		providerNotFound: RequiredParams<'name'>
		/**
		 * N​o​ ​s​e​r​v​e​r​ ​f​o​u​n​d​ ​i​n​ ​t​h​a​t​ ​p​r​o​v​i​d​e​r​.
		 */
		noneFoundInProvider: string
		/**
		 * W​h​i​c​h​ ​s​e​r​v​e​r​s​ ​s​h​o​u​l​d​ ​b​e​ ​i​m​p​o​r​t​e​d​?
		 */
		selectServers: string
		/**
		 * N​o​ ​s​e​r​v​e​r​s​ ​s​e​l​e​c​t​e​d​.
		 */
		noneSelected: string
		/**
		 * {​c​o​u​n​t​}​ ​s​e​r​v​e​r​(​s​)​ ​i​m​p​o​r​t​e​d​ ​i​n​t​o​ ​.​m​c​p​x​.​j​s​o​n
		 * @param {number} count
		 */
		importedIntoConfig: RequiredParams<'count'>
		/**
		 * S​y​n​c​ ​w​i​t​h​ ​t​h​e​ ​c​o​n​f​i​g​u​r​e​d​ ​p​r​o​v​i​d​e​r​s​ ​n​o​w​?
		 */
		syncNow: string
		/**
		 * C​r​e​a​t​e​d
		 */
		createdLabel: string
		/**
		 * U​p​d​a​t​e​d
		 */
		updatedLabel: string
		/**
		 * {​a​c​t​i​o​n​}​:​ ​{​f​i​l​e​P​a​t​h​}
		 * @param {unknown} action
		 * @param {unknown} filePath
		 */
		syncResult: RequiredParams<'action' | 'filePath'>
	}
}

export type TranslationFunctions = {
	cli: {
		/**
		 * Interactive CLI for configuring MCP servers for multiple AI providers
		 */
		description: () => LocalizedString
		options: {
			/**
			 * Project directory
			 */
			projectDirectory: () => LocalizedString
			/**
			 * Show verbose logs
			 */
			verbose: () => LocalizedString
		}
		commands: {
			/**
			 * Interactive wizard for initial setup
			 */
			init: () => LocalizedString
			/**
			 * Add an MCP server
			 */
			add: () => LocalizedString
			/**
			 * Remove an MCP server
			 */
			remove: () => LocalizedString
			/**
			 * List configured MCP servers
			 */
			list: () => LocalizedString
			/**
			 * Regenerate provider configuration files
			 */
			sync: () => LocalizedString
			/**
			 * Import configuration from an existing provider
			 */
			'import': () => LocalizedString
			/**
			 * Show provider synchronization status
			 */
			status: () => LocalizedString
			/**
			 * Server name
			 */
			serverName: () => LocalizedString
			/**
			 * Provider name
			 */
			providerName: () => LocalizedString
		}
	}
	common: {
		/**
		 * No .mcpx.json found in this directory.
		 */
		noConfigFound: () => LocalizedString
		/**
		 * Run "mcpx init" to create a configuration.
		 */
		runInit: () => LocalizedString
		/**
		 * Operation cancelled.
		 */
		operationCancelled: () => LocalizedString
		/**
		 * none
		 */
		none: () => LocalizedString
		/**
		 * See you later!
		 */
		farewell: () => LocalizedString
	}
	wizard: {
		/**
		 * MCPX - MCP server configuration
		 */
		intro: () => LocalizedString
		/**
		 * Configuration found: {serverCount} server(s), {providerCount} provider(s)
		 */
		existingConfigFound: (arg: { providerCount: number, serverCount: number }) => LocalizedString
		/**
		 * What would you like to do?
		 */
		actionPrompt: () => LocalizedString
		actions: {
			/**
			 * Add server
			 */
			addServer: () => LocalizedString
			/**
			 * Remove server
			 */
			removeServer: () => LocalizedString
			/**
			 * Change providers
			 */
			changeProviders: () => LocalizedString
			/**
			 * Sync configs
			 */
			syncConfigs: () => LocalizedString
			/**
			 * Exit
			 */
			exit: () => LocalizedString
		}
		/**
		 * No server to remove.
		 */
		noServerToRemove: () => LocalizedString
		/**
		 * Which server should be removed?
		 */
		removeServerPrompt: () => LocalizedString
		/**
		 * Confirm removal of "{name}"?
		 */
		confirmRemove: (arg: { name: unknown }) => LocalizedString
		/**
		 * Server "{name}" added.
		 */
		serverAdded: (arg: { name: unknown }) => LocalizedString
		/**
		 * Server "{name}" removed.
		 */
		serverRemoved: (arg: { name: unknown }) => LocalizedString
		/**
		 * Providers updated.
		 */
		providersUpdated: () => LocalizedString
		/**
		 * Detected MCP configurations
		 */
		detectedConfigsTitle: () => LocalizedString
		/**
		 * {provider} - {count} server(s)
		 */
		detectedConfigLine: (arg: { count: number, provider: unknown }) => LocalizedString
		/**
		 * Import these configurations?
		 */
		importDetectedConfigs: () => LocalizedString
		/**
		 * {count} server(s) imported.
		 */
		importedServers: (arg: { count: number }) => LocalizedString
		/**
		 * Let's configure your MCP servers.
		 */
		setupServers: () => LocalizedString
		/**
		 * Add another server?
		 */
		addAnotherServer: () => LocalizedString
		/**
		 * No provider selected.
		 */
		noProviderSelected: () => LocalizedString
		/**
		 * Summary
		 */
		summaryTitle: () => LocalizedString
		/**
		 * Servers: {servers}
	Providers: {providers}
		 */
		summaryBody: (arg: { providers: unknown, servers: unknown }) => LocalizedString
		/**
		 * Confirm and generate files?
		 */
		confirmGenerateFiles: () => LocalizedString
		/**
		 * Created: .mcpx.json
		 */
		configCreated: () => LocalizedString
		/**
		 * Configuration complete!
		 */
		setupCompleted: () => LocalizedString
		/**
		 * Created: {filePath}
		 */
		syncCreated: (arg: { filePath: unknown }) => LocalizedString
		/**
		 * Updated: {filePath}
		 */
		syncUpdated: (arg: { filePath: unknown }) => LocalizedString
		/**
		 * Removed: {filePath}
		 */
		syncRemoved: (arg: { filePath: unknown }) => LocalizedString
		/**
		 * {filePath}: {error}
		 */
		syncError: (arg: { error: unknown, filePath: unknown }) => LocalizedString
		/**
		 * Configured the "copilot" shell alias (run "source ~/.zshrc" or restart the terminal).
		 */
		copilotAliasConfigured: () => LocalizedString
	}
	serverWizard: {
		/**
		 * MCP server name
		 */
		nameMessage: () => LocalizedString
		/**
		 * e.g. github, jira, my-server
		 */
		namePlaceholder: () => LocalizedString
		/**
		 * Name is required.
		 */
		nameRequired: () => LocalizedString
		/**
		 * Use letters, numbers, dots, hyphens, or underscores.
		 */
		invalidName: () => LocalizedString
		/**
		 * "{name}" already exists.
		 */
		nameAlreadyExists: (arg: { name: unknown }) => LocalizedString
		/**
		 * Transport type
		 */
		transportMessage: () => LocalizedString
		/**
		 * local command
		 */
		stdioHint: () => LocalizedString
		/**
		 * remote server
		 */
		httpHint: () => LocalizedString
		/**
		 * Command
		 */
		commandMessage: () => LocalizedString
		/**
		 * e.g. npx, uvx, docker
		 */
		commandPlaceholder: () => LocalizedString
		/**
		 * Arguments
		 */
		argsMessage: () => LocalizedString
		/**
		 * comma-separated, leave empty for none
		 */
		argsPlaceholder: () => LocalizedString
		/**
		 * Add environment variables?
		 */
		addEnv: () => LocalizedString
		/**
		 * Variable name
		 */
		envNameMessage: () => LocalizedString
		/**
		 * e.g. API_KEY
		 */
		envNamePlaceholder: () => LocalizedString
		/**
		 * Value for {name}
		 */
		envValueMessage: (arg: { name: unknown }) => LocalizedString
		/**
		 * Add another variable?
		 */
		addAnotherEnv: () => LocalizedString
		/**
		 * Server URL
		 */
		urlMessage: () => LocalizedString
		/**
		 * https://mcp.example.com/api
		 */
		urlPlaceholder: () => LocalizedString
		/**
		 * Add headers?
		 */
		addHeaders: () => LocalizedString
		/**
		 * Header name
		 */
		headerNameMessage: () => LocalizedString
		/**
		 * e.g. Authorization
		 */
		headerNamePlaceholder: () => LocalizedString
		/**
		 * Value for {name}
		 */
		headerValueMessage: (arg: { name: unknown }) => LocalizedString
		/**
		 * Add another header?
		 */
		addAnotherHeader: () => LocalizedString
		/**
		 * Description (optional)
		 */
		descriptionMessage: () => LocalizedString
		/**
		 * brief server description
		 */
		descriptionPlaceholder: () => LocalizedString
	}
	providerWizard: {
		/**
		 * Select the providers to generate configuration for
		 */
		selectProviders: () => LocalizedString
		/**
		 * global
		 */
		globalHint: () => LocalizedString
	}
	addCommand: {
		/**
		 * Server "{name}" already exists. Use a different name.
		 */
		serverAlreadyExists: (arg: { name: unknown }) => LocalizedString
		/**
		 * Server "{name}" added to .mcpx.json
		 */
		serverAddedToConfig: (arg: { name: unknown }) => LocalizedString
		/**
		 * Updated: {filePath}
		 */
		updatedFile: (arg: { filePath: unknown }) => LocalizedString
	}
	removeCommand: {
		/**
		 * No MCP server configured.
		 */
		noServerConfigured: () => LocalizedString
		/**
		 * Which server would you like to remove?
		 */
		selectServer: () => LocalizedString
		/**
		 * Confirm removal of server "{name}"?
		 */
		confirmRemoval: (arg: { name: unknown }) => LocalizedString
		/**
		 * Server "{name}" removed.
		 */
		serverRemoved: (arg: { name: unknown }) => LocalizedString
		/**
		 * Updated: {filePath}
		 */
		updatedFile: (arg: { filePath: unknown }) => LocalizedString
	}
	listCommand: {
		/**
		 * No MCP server configured.
		 */
		noServerConfigured: () => LocalizedString
		/**
		 *  [disabled]
		 */
		disabledSuffix: () => LocalizedString
		/**
		 * MCP servers
		 */
		title: () => LocalizedString
		/**
		 * Enabled providers: {providers}
		 */
		enabledProviders: (arg: { providers: unknown }) => LocalizedString
	}
	statusCommand: {
		/**
		 * missing
		 */
		missing: () => LocalizedString
		/**
		 * in sync
		 */
		inSync: () => LocalizedString
		/**
		 * out of sync
		 */
		outOfSync: () => LocalizedString
		/**
		 * {serverCount} server(s), {providerCount} provider(s)
		 */
		summaryTitle: (arg: { providerCount: number, serverCount: number }) => LocalizedString
		/**
		 * Some providers are out of date. Run "mcpx sync" to update them.
		 */
		someOutdated: () => LocalizedString
		/**
		 * All providers are synchronized.
		 */
		allSynced: () => LocalizedString
	}
	syncCommand: {
		/**
		 * No provider configured.
		 */
		noProviderConfigured: () => LocalizedString
		/**
		 * Syncing configurations...
		 */
		syncing: () => LocalizedString
		/**
		 * Synchronization complete.
		 */
		syncComplete: () => LocalizedString
		/**
		 * {filePath} (created)
		 */
		created: (arg: { filePath: unknown }) => LocalizedString
		/**
		 * {filePath} (updated)
		 */
		updated: (arg: { filePath: unknown }) => LocalizedString
		/**
		 * {filePath} (unchanged)
		 */
		unchanged: (arg: { filePath: unknown }) => LocalizedString
		/**
		 * {filePath} (removed)
		 */
		deleted: (arg: { filePath: unknown }) => LocalizedString
		/**
		 * {count} created
		 */
		createdCount: (arg: { count: number }) => LocalizedString
		/**
		 * {count} updated
		 */
		updatedCount: (arg: { count: number }) => LocalizedString
		/**
		 * {count} removed
		 */
		deletedCount: (arg: { count: number }) => LocalizedString
		/**
		 * {count} unchanged
		 */
		unchangedCount: (arg: { count: number }) => LocalizedString
		/**
		 * {count} error(s)
		 */
		errorCount: (arg: { count: number }) => LocalizedString
		/**
		 * {count} providers processed ({parts})
		 */
		summary: (arg: { count: number, parts: unknown }) => LocalizedString
		/**
		 * Configured the "copilot" shell alias (run "source ~/.zshrc" or restart the terminal).
		 */
		copilotAliasConfigured: () => LocalizedString
	}
	importCommand: {
		/**
		 * No existing MCP configuration detected in this directory.
		 */
		noneDetected: () => LocalizedString
		/**
		 * Detected configurations
		 */
		detectedTitle: () => LocalizedString
		/**
		 * {provider} ({filePath}) - {count} server(s)
		 */
		detectedLine: (arg: { count: number, filePath: unknown, provider: unknown }) => LocalizedString
		/**
		 * Which provider should be imported?
		 */
		selectProvider: () => LocalizedString
		/**
		 * {count} server(s)
		 */
		providerHint: (arg: { count: number }) => LocalizedString
		/**
		 * Provider "{name}" not found.
		 */
		providerNotFound: (arg: { name: unknown }) => LocalizedString
		/**
		 * No server found in that provider.
		 */
		noneFoundInProvider: () => LocalizedString
		/**
		 * Which servers should be imported?
		 */
		selectServers: () => LocalizedString
		/**
		 * No servers selected.
		 */
		noneSelected: () => LocalizedString
		/**
		 * {count} server(s) imported into .mcpx.json
		 */
		importedIntoConfig: (arg: { count: number }) => LocalizedString
		/**
		 * Sync with the configured providers now?
		 */
		syncNow: () => LocalizedString
		/**
		 * Created
		 */
		createdLabel: () => LocalizedString
		/**
		 * Updated
		 */
		updatedLabel: () => LocalizedString
		/**
		 * {action}: {filePath}
		 */
		syncResult: (arg: { action: unknown, filePath: unknown }) => LocalizedString
	}
}

export type Formatters = {}
